# Generated by Django 6.0.7 on 2026-07-22 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=16, unique=True, verbose_name='工号')),
                ('display_name', models.CharField(max_length=80, verbose_name='姓名')),
                ('department', models.CharField(max_length=120, verbose_name='部门')),
                ('access_scope', models.CharField(default='department', max_length=32, verbose_name='数据范围')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='首次登录修改密码')),
                ('allow_employee_id_login', models.BooleanField(default=False, verbose_name='允许工号登录')),
                ('source_reference', models.CharField(blank=True, max_length=255, verbose_name='名单来源')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eccp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ECCP 用户档案',
                'verbose_name_plural': 'ECCP 用户档案',
                'permissions': [('access_workspace', '访问 ECCP 工作台'), ('use_ai_assistant', '使用 AI 助手'), ('create_content', '创建和编辑内容'), ('manage_projects', '管理内容项目'), ('view_tasks', '查看和处理任务'), ('view_topics', '查看和搜索选题'), ('view_knowledge', '查看知识库'), ('view_analytics', '查看数据概览'), ('manage_platform', '管理 Agent、Skill、连接和系统设置')],
            },
        ),
    ]
