# Generated by Django 6.0.7 on 2026-07-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_job_title_userprofile_section_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDirectory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_id", models.CharField(max_length=16, unique=True, verbose_name="工号")),
                ("full_name", models.CharField(max_length=80, verbose_name="姓名")),
                ("department", models.CharField(max_length=120, verbose_name="部门")),
                ("section", models.CharField(blank=True, max_length=160, verbose_name="科室")),
                ("team", models.CharField(blank=True, max_length=200, verbose_name="系/班组")),
                ("assignment_department", models.CharField(blank=True, max_length=200, verbose_name="借调/轮岗部门")),
                ("job_title", models.CharField(blank=True, max_length=80, verbose_name="职务")),
                ("is_active", models.BooleanField(default=True, verbose_name="在职")),
                ("registration_enabled", models.BooleanField(default=True, verbose_name="允许自助注册")),
                ("source_reference", models.CharField(blank=True, max_length=255, verbose_name="名单来源")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "claimed_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_directory_record",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="已注册账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工目录",
                "verbose_name_plural": "员工目录",
                "ordering": ("employee_id",),
            },
        ),
    ]
